In [70]:
import numpy as np

In [71]:
list1 = [1,2,3,4]
a = np.array(list)

In [72]:
b = np.array([
    [1,2,3],
    [4,5,6]
])
print(b.shape)
print(b[0,0])

(2, 3)
1


In [73]:
lst = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
arr = np.array(lst)
arr

a = arr[1:, 1:]
print(a)

[[5 6]
 [8 9]]


In [74]:
a =arr[0:2, 0:2]
print(a)
a= arr[1:, 1:]
print(a)

[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


In [75]:
bool_array = np.array([
    [False, True, False],
    [True, False, True],
    [False, True, False]
])

In [78]:
n = a[bool_array]
print(n)

[2 4 6 8]


In [79]:
a = np.array(lst)
bool_indexing = (a%2 == 0)
print(bool_indexing)
print(a[bool_indexing])

[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


In [84]:
print(a[bool_indexing])
b = a[a%2==0]

[2 4 6 8]


## 각요소 연산

In [139]:
a = np.arange(4)
b = np.arange(4,8)
print(a.reshape(2,2))
print(b.reshape(2,2))

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [127]:
#c = a+b
c = np.add(a,b)
print(c)

[ 4  6  8 10]


In [128]:
#c = a-b
c = np.subtract(a,b)
print(c)

[-4 -4 -4 -4]


In [119]:
#c = a*b
c = np.multiply(a,b)
print(c)

[ 0  5 12 21]


In [120]:
#c = a/b
c = np.divide(a,b)
print(c)

[0.         0.2        0.33333333 0.42857143]
